### ISSUE TITLE
What's the purpose of this module?

### ISSUE THREAD

**Issue by chiefGui** [inuitcss/generic.normalize#11]
Quoting from the README:

> The normalize.css module is an exact clone [...]

Is there any reason for this module to exist?

**Comment by nenadjelovac** [comment]
I think it's because of following two reasons:
1. There's no scss version fo normalize.css
2. Normalize.css is not versioned on bower.

**Comment by chiefGui** [comment]
Oh, I see.

But just searching a little, we actually have the two at once: https://github.com/JohnAlbin/normalize-scss

Versioned on bower plus .scss.

Not complaining. I just think that's worth to mention since sometimes you're maintaining an unneeded library.

**Comment by nenadjelovac** [comment]
@chiefGui Well, good thing about inuitcss is that you can use that one and don't care about inuit version.

> I just think that's worth to mention since sometimes you're maintaining an unneeded library.

I get it. It's worth thinking about. Thanks.
