### ISSUE TITLE
using generic.box-sizing breaks normalize styles.

### ISSUE THREAD

**Issue by lifeiscontent** [inuitcss/generic.normalize#2]
there is a input[type="search"] style in normalize that doesn't get reset by the box-sizing module and there for will make funny padding on search inputs if you have them styled.

**Comment by anselmh** [comment]
Hey, thanks for reporting this here. As this package is only a wrapper for the original repository it doesn’t make sense to report here.

I do think it’s [related/similar to this issue](https://github.com/necolas/normalize.css/issues/360), isn’t it? If so, you may take part in the discussion over there (please have a look at the linked issues in there, too).

Again, thanks for reporting but I’m closing this for now as it’s nothing we can change over here.
