### ISSUE TITLE
Import directly from main project repository

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/generic.normalize#6]
Hi @csswizardry,

I think you can remove this package from inuitcss and just import normalise.css from main repository : it'll be easier for maintenance...

For beginner, you can create a small documentation and code exemple in a starter-kit.

What's your opinion ? cc @nenadjelovac @anselmh @csshugs

**Comment by nenadjelovac** [comment]
@florianbouvot they don't have scss version of normalize at the moment. So you would have to use something like https://github.com/chriseppstein/sass-css-importer (which depends on ruby) to import it in your main scss file (and not end up with `@import "normalize.css"` at the top of your compiled css file).

**Comment by anselmh** [comment]
I'd vote for using the official package via npm but it's not written in sass.

----
Anselm

**Comment by csshugs** [comment]
@florianbouvot @nenadjelovac @anselmh 
As I am aware, you cannot @import .css files in Sass, so at the moment I don't see any alternative than continue doing it manually this way until there is an official Sass port of normalize.

___

> So you would have to use something like https://github.com/chriseppstein/sass-css-importer 

This would do the trick but brings to much complexity, so it's not really an option to me.

**Comment by florianbouvot** [comment]
Sorry, you're right it's not possible at the moment ;)

**Comment by nenadjelovac** [comment]
@csshugs 
>This would do the trick but brings to much complexity, so it's not really an option to me.

Agreed. We should probably spam them to make `.scss` version :)

**Comment by florianbouvot** [comment]
@csshugs @nenadjelovac there will be no Sass version of Normalize.css so we will continue manually ;)
