### ISSUE TITLE
Problems with dependencies and naming

### ISSUE THREAD

**Issue by sarukuku** [inuitcss/generic.normalize#7]
I created a simple bower.json test file with bower init and installed two inuit bower packages as dependencies by running commands

```
bower install --save inuit-tables
bower install --save inuit-normalize
```

The resulting bower.json file looks like this:

```
{
  "name": "TEST",
  "version": "0.0.1",
  "authors": [
    "sarukuku <joonas.salovaara@gmail.com>"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "inuit-normalize.css": "inuit-normalize#~3.0.3",
    "inuit-tables": "~0.2.1"
  }
}
```

If you now list the content of the `bower_components` folder it looks like this:

```
drwxr-xr-x  7 Joonas  staff  238  1 Lok 15:10 inuit-defaults
drwxr-xr-x  6 Joonas  staff  204  1 Lok 15:10 inuit-functions
drwxr-xr-x  7 Joonas  staff  238  1 Lok 15:10 inuit-normalize
drwxr-xr-x  7 Joonas  staff  238  1 Lok 15:11 inuit-normalize.css
drwxr-xr-x  7 Joonas  staff  238  1 Lok 15:10 inuit-tables
```

It pulls down dependencies it needs but the inuit-normalize seems to be pulled in twice with a different folder name: inuit-normalize & inuit-normalize.css. The only difference I noticed when quickly looking through the two directories and their contents is the directory name.

I wonder if there's something a bit off with the package naming & dependencies?

**Comment by csshugs** [comment]
@sarukuku 
The correct and up-to-date package is **"inuit-normalize.css"**.
"inuit-normalize" is being downloaded because it's set as a dependency in an older version (3.0.1) in "inuit-tables" (in its bower.json), where the package was still named without "*.css".
But both folders reference to the same repository and the same version of it, so it doesn't really matter which one you use. So there shouldn't be any differences other than the naming of the folder.

**Comment by sarukuku** [comment]
@csshugs Though having the same code in two differently named folders is a minor nuisance isn't it a bad practice as it unnecessarily duplicates code? Could the dependency in `inuit-tables` be updated?

**Comment by csshugs** [comment]
> Could the dependency in inuit-tables be updated?

@sarukuku 
Yeah, you're right. It's a minor bug in "inuit-tables". 
Although it wont hurt anybody, fixing it would prevent any possible issues in the future. 
I'm going to provide a Pull Request for that.

Thanks for pointing it out!

**Comment by sarukuku** [comment]
@csshugs  :+1:

**Comment by csshugs** [comment]
@sarukuku 
Due to the fact that this is an issue of the "objects.tables" repository, can you close this issue?

**Comment by sarukuku** [comment]
@csshugs sure! Rest of the conversation related to this issue continued [here](https://github.com/inuitcss/objects.tables/pull/3).

**Comment by csshugs** [comment]
:+1:
