### ISSUE TITLE
Normalize is now version 4.0.0

### ISSUE THREAD

**Issue by fardormu** [inuitcss/generic.normalize#9]
Recently, the author released a new [version](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#400-march-19-2016).

Would it be appropriate to update it here as well?

**Comment by csshugs** [comment]
@fardormu I quickly opened an equivalent [Pull Request](https://github.com/inuitcss/generic.normalize/pull/10) for this issue. Do you mind closing this issue again and we can transfer any potential discussion over to the PR #10 ?

**Comment by fardormu** [comment]
@csshugs sure!

**Comment by csshugs** [comment]
@fardormu Thanks :+1:
